# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4130e509364c45aecdb8c01e8d037ce027d15f47c13feb55c7b06b0fa388688079b38c518a81600f0c2bee4359cc503970611921e0b40c1934541be870dea612

test:
  secret_key_base: 220495f5cdfba6a83c70eccd126433f7e72906b7a78bbca4076d95ccc3c7d195c3f623fe893dfa7ec8e44353740edca67efb3457f44ed299089d7582f7823cea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
