source 'https://rubygems.org'

#Core Libraries
gem 'rails', '>= 5.0.0.beta3', '< 5.1'
gem 'sqlite3' #will switch to postgres soon
# gem 'unicorn'

#Front End Tools
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'simple_form'

#Debugging & Test Suite
group :development, :test do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
end

group :development do
  gem 'spring'
end

gem 'turbolinks', '~> 5.x'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
